version: "3.8"
services:
  backend:
    build: learnerReportCS_backend/
    ports:
      - "3001:3001"
  
  frontend:
    build: learnerReportCS_frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend


networks:
  application:
    driver: bridge